CC=gcc
unnamed_pipe named_pipe daemon : unnamed_pipe.c named_pipe.c daemon.c
	gcc -std=c99 -Wall -o unnamed_pipe unnamed_pipe.c
	gcc -std=c99 -Wall -o named_pipe named_pipe.c
	gcc -Wall -o daemon daemon.c
